### ISSUE TITLE
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

### ISSUE THREAD

**Issue by lilechao** [gensx-x1/ApeWatch#2]
Hello, this will be reported when the program runs

eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

**Comment by gensx-x1** [comment]
yeah i aware of this issue , will update with fix soon

**Comment by gensx-x1** [comment]
i figured out temporary solution for this. it shouldn't throw this error now
